-- Add permission fields to CompanyUser table
ALTER TABLE "CompanyUser" ADD COLUMN IF NOT EXISTS "canRead" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "CompanyUser" ADD COLUMN IF NOT EXISTS "canEdit" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "CompanyUser" ADD COLUMN IF NOT EXISTS "canExport" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "CompanyUser" ADD COLUMN IF NOT EXISTS "canBTW" BOOLEAN NOT NULL DEFAULT false;
